#!/usr/bin/env node
// codegen-states.mjs — Single source of truth for canonical state model.
// Risk r8 / Kaizen K-2026-05-29-5. Reads templates/states.yml, emits gen/states.{json,js,go}.
// Schema: list of states with { id, label, aliases[], description, dashboard_group }.
//
// Usage:
//   node scripts/codegen-states.mjs                                # uses templates/states.yml, writes gen/
//   node scripts/codegen-states.mjs --input <file> --out-dir <dir>
//
// CI integration: run after states.yml changes, fail build if `git diff --exit-code gen/`.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

// ---- minimal YAML parser for our subset (list-of-state-objects schema) -----
function parseStatesYaml(src) {
  const states = [];
  let cur = null;
  for (const rawLine of src.split(/\r?\n/)) {
    if (!rawLine.trim() || rawLine.trim().startsWith('#')) continue;
    const m1 = rawLine.match(/^\s*-\s*id:\s*(.+?)\s*$/);
    if (m1) {
      cur = { id: m1[1].replace(/^["']|["']$/g, ''), aliases: [] };
      states.push(cur);
      continue;
    }
    if (!cur) continue;
    const m2 = rawLine.match(/^\s+(label|description|dashboard_group):\s*(.+?)\s*$/);
    if (m2) {
      cur[m2[1]] = m2[2].replace(/^["']|["']$/g, '');
      continue;
    }
    const m3 = rawLine.match(/^\s+aliases:\s*\[(.*)\]\s*$/);
    if (m3) {
      cur.aliases = m3[1].split(',').map(s => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
      continue;
    }
  }
  return states;
}

// ---- args -----------------------------------------------------------------
const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, x, i, a) => {
    if (x.startsWith('--')) acc.push([x.slice(2), a[i + 1]]);
    return acc;
  }, [])
);
const input = args.input || resolve(repoRoot, 'templates', 'states.yml');
const outDir = args['out-dir'] || resolve(repoRoot, 'gen');

if (!existsSync(input)) {
  console.error('Input not found: ' + input);
  process.exit(2);
}
mkdirSync(outDir, { recursive: true });

const src = readFileSync(input, 'utf8');
// Strip YAML "states:" header by parsing only block list items beneath it
const states = parseStatesYaml(src);

if (states.length === 0) {
  console.error('No states parsed. Check states.yml schema.');
  process.exit(3);
}

// Derive flat structures
const canonical = states.map(s => s.id);
const aliases = {};
const groups = {};
for (const s of states) {
  for (const a of (s.aliases || [])) aliases[a.toLowerCase()] = s.id;
  const g = s.dashboard_group || s.id;
  if (!groups[g]) groups[g] = [];
  groups[g].push(s.id);
}

// ---- emit gen/states.json -------------------------------------------------
writeFileSync(resolve(outDir, 'states.json'),
  JSON.stringify({ canonical, aliases, groups, states }, null, 2) + '\n');
console.log('wrote states.json (' + canonical.length + ' states, ' + Object.keys(aliases).length + ' aliases)');

// ---- emit gen/states.js ---------------------------------------------------
const jsLines = [];
jsLines.push('// AUTOGENERATED by scripts/codegen-states.mjs - DO NOT EDIT');
jsLines.push('export const CANONICAL = ' + JSON.stringify(canonical, null, 2) + ';');
jsLines.push('export const VALID_IDS = CANONICAL; // alias for auto-submit.mjs (B-fix 2026-06-12)');
jsLines.push('export const ALIASES = ' + JSON.stringify(aliases, null, 2) + ';');
jsLines.push('export const GROUPS = ' + JSON.stringify(groups, null, 2) + ';');
jsLines.push('export const STATES = ' + JSON.stringify(states, null, 2) + ';');
jsLines.push('export function canonicalize(raw) {');
jsLines.push('  if (raw == null) return raw;');
jsLines.push('  const k = String(raw).toLowerCase().trim();');
jsLines.push('  return ALIASES[k] || (CANONICAL.includes(k) ? k : null);');
jsLines.push('}');
writeFileSync(resolve(outDir, 'states.js'), jsLines.join('\n') + '\n');
console.log('wrote states.js');

// ---- emit gen/states.go ---------------------------------------------------
const goSlice = (arr) => '[]string{' + arr.map(s => '"' + s + '"').join(', ') + '}';
const goEntries = (obj) => Object.entries(obj).map(([k, v]) =>
  '\t"' + k + '": ' + (Array.isArray(v) ? goSlice(v) : '"' + v + '"') + ',');

const goLines = [];
goLines.push('// AUTOGENERATED by scripts/codegen-states.mjs - DO NOT EDIT');
goLines.push('// Source: templates/states.yml');
goLines.push('package data');
goLines.push('');
goLines.push('var CanonicalStates = ' + goSlice(canonical));
goLines.push('');
goLines.push('var StateAliases = map[string]string{');
for (const [k, v] of Object.entries(aliases)) goLines.push('\t"' + k + '": "' + v + '",');
goLines.push('}');
goLines.push('');
goLines.push('var DashboardGroups = map[string][]string{');
for (const [k, v] of Object.entries(groups)) goLines.push('\t"' + k + '": ' + goSlice(v) + ',');
goLines.push('}');
goLines.push('');
goLines.push('// Canonicalize resolves an alias or canonical id; returns "" if unknown.');
goLines.push('func Canonicalize(raw string) string {');
goLines.push('\tif v, ok := StateAliases[raw]; ok { return v }');
goLines.push('\tfor _, s := range CanonicalStates { if s == raw { return s } }');
goLines.push('\treturn ""');
goLines.push('}');
writeFileSync(resolve(outDir, 'states.go'), goLines.join('\n') + '\n');
console.log('wrote states.go');

console.log('Done.');
