#!/usr/bin/env node
/**
 * readiness-scorer.mjs — Harvard MCS standards checker for resume + cover letter
 *
 * Exports:
 *   scoreResume(resumeText, jdKeywords)         → { score, max:60, checks, flags }
 *   scoreCoverLetter(clText, company, keywords) → { score, max:40, checks, flags, cleanpaste_reminder }
 *   scoreCard(card, { resumeText, clText })     → { total, grade, passed, resume, cover_letter, flags, ... }
 *
 * CLI (via npm run score:card / score:dry-run):
 *   node scripts/readiness-scorer.mjs [--dry-run] [--card-ids id1,id2,...] [--kanban-json <path>]
 *   Writes data/readiness-scores.json and data/readiness-results-YYYY-MM-DD.json
 */

import fs   from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const ROOT       = path.resolve(__dirname, '..');
const DATA       = path.join(ROOT, 'data');
const DATE_STAMP = new Date().toISOString().slice(0, 10);

// ── Standards loader ──────────────────────────────────────────────────────────

let _standards = null;
function getStandards() {
  if (!_standards) {
    _standards = JSON.parse(
      fs.readFileSync(path.join(ROOT, 'config', 'readiness-standards.json'), 'utf8'),
    );
  }
  return _standards;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function toBulletLines(text) {
  return text.split('\n').filter((l) => /^\s*[-•*]\s/.test(l));
}

function startsWithVerb(line, verbs) {
  const clean = line.replace(/^\s*[-•*]\s*/, '').trim();
  const first = (clean.split(/\s+/)[0] ?? '').replace(/[^a-zA-Z]/g, '');
  return verbs.some((v) => v.toLowerCase() === first.toLowerCase());
}

function hasQuantification(line) {
  return /\d+%|\$[\d,]+|\d+[xX]|\b\d{2,}\b/.test(line);
}

function getGrade(score, thresholds) {
  if (score >= thresholds.A) return 'A';
  if (score >= thresholds.B) return 'B';
  if (score >= thresholds.C) return 'C';
  return 'D';
}

function loadCvText() {
  const cvPath = path.join(ROOT, 'cv.md');
  if (fs.existsSync(cvPath)) return fs.readFileSync(cvPath, 'utf8');
  return null;
}

function findClFileForCard(card) {
  // Look in BOTH cover-letters/ (curated) AND output/ (generated by generate-cl
  // --all, which writes cl_{slug}_*.txt). Previously only cover-letters/ was
  // searched, so freshly generated CLs were invisible and A/B cards were held
  // for "no cover letter found" even after Step 4.55 created one. (K-2026-06-21-1)
  const slug = (card.company || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  if (!slug) return null;
  for (const dir of ['cover-letters', 'output']) {
    const d = path.join(ROOT, dir);
    if (!fs.existsSync(d)) continue;
    const files = fs.readdirSync(d).filter(
      (f) => f.includes(slug) && (f.endsWith('.md') || f.endsWith('.txt')),
    );
    if (files.length > 0) return path.join(d, files[0]);
  }
  return null;
}

function readFileOrNull(filePath) {
  if (!filePath || !fs.existsSync(filePath)) return null;
  try { return fs.readFileSync(filePath, 'utf8'); } catch { return null; }
}

function writeJSON(filePath, data) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tmp = filePath + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + '\n', 'utf8');
  fs.renameSync(tmp, filePath);
}

// ── Resume scorer (60 pts) ────────────────────────────────────────────────────

/**
 * Score a resume text against Harvard MCS standards.
 * @param {string}   resumeText   Full text of the resume (markdown or plain text)
 * @param {string[]} jdKeywords   Keywords extracted from the job description
 * @returns {{ score, max, checks, flags }}
 */
export function scoreResume(resumeText, jdKeywords = []) {
  const { action_verbs: verbs, resume: resumeStds, scoring } = getStandards();
  const { no_personal_pronouns } = resumeStds.language;

  const bullets = toBulletLines(resumeText);

  // ─── Pronouns (10 pts): −2 per violating bullet, min 0 ─────────────────────
  const pronounRe = new RegExp(`\\b(${no_personal_pronouns.join('|')})\\b`, 'i');
  const violations = bullets.filter((l) => pronounRe.test(l));
  const pronounScore = Math.max(0, 10 - violations.length * 2);

  // ─── Action verbs (15 pts): 100%=15, ≥80%=12, ≥60%=9, <60%=0 ──────────────
  const verbBullets = bullets.filter((l) => startsWithVerb(l, verbs));
  const verbPct = bullets.length > 0 ? Math.round((verbBullets.length / bullets.length) * 100) : 0;
  const verbScore = verbPct >= 100 ? 15 : verbPct >= 80 ? 12 : verbPct >= 60 ? 9 : 0;

  // ─── Quantification (10 pts): ≥50%=10, ≥25%=6, <25%=2 ─────────────────────
  const quantBullets = bullets.filter((l) => hasQuantification(l));
  const quantPct = bullets.length > 0 ? Math.round((quantBullets.length / bullets.length) * 100) : 0;
  const quantScore = quantPct >= 50 ? 10 : quantPct >= 25 ? 6 : 2;

  // ─── Structure (10 pts): email+3, phone+3, Experience+2, Education+2 ────────
  const hasEmail = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/.test(resumeText);
  const hasPhone = /\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}/.test(resumeText);
  const hasExp   = /^##?\s*experience\b/im.test(resumeText) || /\bexperience\b/i.test(resumeText);
  const hasEdu   = /^##?\s*education\b/im.test(resumeText)  || /\beducation\b/i.test(resumeText);
  const structScore = (hasEmail ? 3 : 0) + (hasPhone ? 3 : 0) + (hasExp ? 2 : 0) + (hasEdu ? 2 : 0);
  const structMissing = [
    ...(!hasEmail ? ['email'] : []),
    ...(!hasPhone ? ['phone'] : []),
    ...(!hasExp   ? ['Experience section'] : []),
    ...(!hasEdu   ? ['Education section'] : []),
  ];

  // ─── Keyword overlap (15 pts): ≥60%=15, ≥40%=10, ≥20%=5, <20%=0 ────────────
  const textLower  = resumeText.toLowerCase();
  const matched    = jdKeywords.filter((k) => textLower.includes(k.toLowerCase()));
  const missingKw  = jdKeywords.filter((k) => !textLower.includes(k.toLowerCase()));
  const kwPct      = jdKeywords.length > 0 ? Math.round((matched.length / jdKeywords.length) * 100) : 60;
  const kwScore    = kwPct >= 60 ? 15 : kwPct >= 40 ? 10 : kwPct >= 20 ? 5 : 0;

  const total = pronounScore + verbScore + quantScore + structScore + kwScore;

  const flags = [];
  if (structMissing.length) flags.push(...structMissing.map((m) => `Missing ${m} in resume`));
  if (violations.length)    flags.push(`${violations.length} bullet(s) contain personal pronouns`);
  if (quantPct < 25)        flags.push(`Only ${quantPct}% of bullets quantified`);
  if (verbPct < 60)         flags.push(`Only ${verbPct}% of bullets start with action verbs`);

  return {
    score: total,
    max: 60,
    checks: {
      pronouns: {
        score: pronounScore,
        max: 10,
        violations: violations.map((l) => l.trim().slice(0, 100)),
      },
      action_verbs: { score: verbScore, max: 15, pct: verbPct },
      quantification: { score: quantScore, max: 10, pct: quantPct },
      structure: { score: structScore, max: 10, missing: structMissing },
      keyword_overlap: {
        score: kwScore,
        max: 15,
        matched: matched.slice(0, 20),
        missing: missingKw.slice(0, 20),
        pct: kwPct,
      },
    },
    flags,
  };
}

// ── Cover letter scorer (40 pts) ──────────────────────────────────────────────

/**
 * Score a cover letter against Harvard MCS standards.
 * @param {string}   clText      Full text of the cover letter
 * @param {string}   companyName Company name from the card (for tailoring check)
 * @param {string[]} jdKeywords  Keywords from the job description
 * @returns {{ score, max, checks, flags, cleanpaste_reminder }}
 */
export function scoreCoverLetter(clText, companyName = '', jdKeywords = []) {
  const { action_verbs: verbs } = getStandards();

  // ─── Structure (15 pts) ──────────────────────────────────────────────────────
  const hasDate = /\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2},?\s+\d{4}|\d{1,2}\/\d{1,2}\/\d{4}|\d{4}-\d{2}-\d{2}/.test(clText);
  const hasDear    = /\bdear\b/i.test(clText);
  const hasColon   = /\bdear[^:\n]*:/i.test(clText);
  const paragraphs = clText.split(/\n\s*\n/).filter((p) => p.trim().length > 20);
  const has3Para   = paragraphs.length >= 3;
  const hasClosing = /sincerely|best regards|best wishes|thank you|regards/i.test(clText);
  const structScore = (hasDate ? 3 : 0) + (hasDear ? 3 : 0) + (hasColon ? 2 : 0)
    + (has3Para ? 4 : 0) + (hasClosing ? 3 : 0);

  // ─── Company tailoring (10 pts) ──────────────────────────────────────────────
  const clLower    = clText.toLowerCase();
  const compNorm   = (companyName || '').toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();
  const mentionsCompany = !!compNorm && clLower.includes(compNorm);
  const mentionsRole    = /\b(?:role|position|opportunity|opening)\b/i.test(clText);
  const tailorScore = (mentionsCompany ? 5 : 0) + (mentionsRole ? 5 : 0);

  // ─── JD keyword overlap (10 pts): ≥50%=10, ≥30%=6, <30%=2 ─────────────────
  const kwMatched = jdKeywords.filter((k) => clLower.includes(k.toLowerCase()));
  const kwMissing = jdKeywords.filter((k) => !clLower.includes(k.toLowerCase()));
  const kwPct     = jdKeywords.length > 0 ? Math.round((kwMatched.length / jdKeywords.length) * 100) : 30;
  const kwScore   = kwPct >= 50 ? 10 : kwPct >= 30 ? 6 : 2;

  // ─── Action verbs (5 pts): ≥3 verbs=5, 1–2=3, 0=0 ──────────────────────────
  const verbCount = verbs.filter((v) => new RegExp(`\\b${v}\\b`, 'i').test(clText)).length;
  const verbScore = verbCount >= 3 ? 5 : verbCount >= 1 ? 3 : 0;

  const total = structScore + tailorScore + kwScore + verbScore;

  const flags = [];
  if (!mentionsCompany && companyName) flags.push(`Cover letter doesn't mention company name: "${companyName}"`);
  if (!has3Para) flags.push(`Only ${paragraphs.length} paragraph(s) in cover letter — need 3+`);
  if (kwPct < 30) flags.push(`Only ${kwPct}% of JD keywords appear in cover letter`);

  return {
    score: total,
    max: 40,
    checks: {
      structure: {
        score: structScore,
        max: 15,
        has_date: hasDate,
        has_dear: hasDear,
        has_colon: hasColon,
        has_three_paragraphs: has3Para,
        has_closing: hasClosing,
        paragraph_count: paragraphs.length,
      },
      tailoring: {
        score: tailorScore,
        max: 10,
        mentions_company: mentionsCompany,
        mentions_role: mentionsRole,
      },
      keyword_overlap: {
        score: kwScore,
        max: 10,
        matched: kwMatched.slice(0, 20),
        missing: kwMissing.slice(0, 20),
        pct: kwPct,
      },
      action_verbs: { score: verbScore, max: 5, count: verbCount },
    },
    flags,
    cleanpaste_reminder: true,
  };
}

// ── Card scorer ───────────────────────────────────────────────────────────────

/**
 * Score a card using its resume and cover letter texts.
 * If texts are not provided, attempts to load from standard project paths.
 * Returns score_skipped:true if either text is unavailable.
 *
 * @param {object}  card                 Kanban card with id, company, keywords
 * @param {object}  [opts]
 * @param {string|null} [opts.resumeText] Resume text (null = load cv.md)
 * @param {string|null} [opts.clText]    Cover letter text (null = find by company slug)
 * @returns {Promise<object>}  Score report or { score_skipped: true, reason }
 */
export async function scoreCard(card, { resumeText = null, clText = null } = {}) {
  const { scoring } = getStandards();
  const jdKeywords  = Array.isArray(card.keywords) ? card.keywords : [];
  const cardId      = card.id || 'unknown';

  // Resolve resume text
  const resolvedResume = resumeText ?? loadCvText();

  // Resolve cover letter text
  let resolvedCl = clText;
  if (resolvedCl === null) {
    const clPath = findClFileForCard(card);
    resolvedCl = readFileOrNull(clPath);
  }

  // Skip if either is still missing
  if (!resolvedResume || !resolvedCl) {
    const reason = !resolvedResume
      ? 'resume text not available (cv.md missing)'
      : `no cover letter found for "${card.company}"`;
    console.warn(`[readiness] warn: score_skipped for ${cardId} — ${reason}`);
    return {
      card_id:      cardId,
      timestamp:    new Date().toISOString(),
      score_skipped: true,
      reason,
    };
  }

  const resumeResult = scoreResume(resolvedResume, jdKeywords);
  const clResult     = scoreCoverLetter(resolvedCl, card.company || '', jdKeywords);

  const total  = resumeResult.score + clResult.score;
  const grade  = getGrade(total, scoring.grade_thresholds);
  const passed = total >= scoring.pass_threshold;

  return {
    card_id:          cardId,
    timestamp:        new Date().toISOString(),
    total,
    grade,
    passed,
    resume:           resumeResult,
    cover_letter:     clResult,
    flags:            [...resumeResult.flags, ...clResult.flags],
    cleanpaste_reminder: true,
  };
}

// ── Readiness scores persistence ──────────────────────────────────────────────

const SCORES_PATH = path.join(DATA, 'readiness-scores.json');

export function loadReadinessScores() {
  if (!fs.existsSync(SCORES_PATH)) return {};
  try { return JSON.parse(fs.readFileSync(SCORES_PATH, 'utf8')); } catch { return {}; }
}

export function saveReadinessScore(cardId, total, grade) {
  const scores = loadReadinessScores();
  scores[cardId] = `[readiness:${total}/${grade} ${DATE_STAMP}]`;
  writeJSON(SCORES_PATH, scores);
  return scores[cardId];
}

// ── CLI ───────────────────────────────────────────────────────────────────────

const IS_CLI = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename);

if (IS_CLI) {
  await runCli();
}

async function runCli() {
  const argVal = (flag) => {
    const i = process.argv.indexOf(flag);
    return i !== -1 ? (process.argv[i + 1] ?? null) : null;
  };

  const DRY_RUN    = process.argv.includes('--dry-run');
  const CARD_IDS   = argVal('--card-ids')?.split(',').map((s) => s.trim()).filter(Boolean) ?? null;
  const KANBAN_JSON = argVal('--kanban-json') || null;

  // Load kanban cards
  let cards = [];
  try {
    const importDir  = DATA;
    let source = KANBAN_JSON;

    if (!source) {
      // Try data/board-state.json first (most current), then newest kanban-import
      const boardState = path.join(importDir, 'board-state.json');
      if (fs.existsSync(boardState)) {
        source = boardState;
      } else {
        const imports = fs.readdirSync(importDir)
          .filter((f) => /^kanban-import-\d{4}-\d{2}-\d{2}\.json$/.test(f))
          .sort();
        source = imports.length ? path.join(importDir, imports.at(-1)) : null;
      }
    }

    if (!source || !fs.existsSync(source)) {
      console.error('[readiness] No kanban source found. Run scan first or pass --kanban-json.');
      process.exit(0);
    }

    const raw  = JSON.parse(fs.readFileSync(source, 'utf8'));
    const pool = Array.isArray(raw) ? raw
      : Array.isArray(raw.cards) ? raw.cards
      : raw.cards && typeof raw.cards === 'object' ? Object.values(raw.cards)
      : [];

    cards = pool.filter((c) => c && typeof c === 'object' && c.id);
    if (CARD_IDS) cards = cards.filter((c) => CARD_IDS.includes(c.id));
  } catch (e) {
    console.error(`[readiness] Error loading cards: ${e.message}`);
    process.exit(0);
  }

  if (cards.length === 0) {
    console.log('[readiness] No cards to score.');
    process.exit(0);
  }

  const cvText = loadCvText();
  if (!cvText) {
    console.warn('[readiness] warn: cv.md not found — all cards will be score_skipped');
  }

  console.log(`[readiness] Scoring ${cards.length} card(s)${DRY_RUN ? ' (dry-run)' : ''}...`);

  const passedIds  = [];
  const failedIds  = [];
  const skippedIds = [];
  const results    = [];
  let totalScore   = 0;
  let scoredCount  = 0;

  for (const card of cards) {
    const clPath = findClFileForCard(card);
    const clText = readFileOrNull(clPath);
    const result = await scoreCard(card, { resumeText: cvText, clText });

    if (result.score_skipped) {
      skippedIds.push(card.id);
      console.log(`  [SKIP] ${card.id} — ${card.company}: ${result.reason}`);
    } else if (result.passed) {
      passedIds.push(card.id);
      totalScore += result.total;
      scoredCount++;
      console.log(`  [PASS ${result.total}/${result.grade}] ${card.id} — ${card.company}`);
      if (!DRY_RUN) saveReadinessScore(card.id, result.total, result.grade);
    } else {
      failedIds.push(card.id);
      totalScore += result.total;
      scoredCount++;
      console.log(`  [FAIL ${result.total}/${result.grade}] ${card.id} — ${card.company}`);
      if (result.flags.length) {
        for (const flag of result.flags.slice(0, 3)) console.log(`    • ${flag}`);
      }
      if (!DRY_RUN) saveReadinessScore(card.id, result.total, result.grade);
    }
    results.push(result);
  }

  const avgScore = scoredCount > 0 ? Math.round(totalScore / scoredCount) : 0;
  const avgGrade = scoredCount > 0 ? getGrade(avgScore, getStandards().scoring.grade_thresholds) : 'N/A';

  console.log('');
  console.log(`[readiness] ${passedIds.length}/${cards.length} cards passed readiness (avg ${avgScore}/${avgGrade})`);
  if (failedIds.length) console.log(`[readiness] ${failedIds.length} failed: ${failedIds.join(', ')}`);
  if (skippedIds.length) console.log(`[readiness] ${skippedIds.length} skipped (no cv.md or CL found): ${skippedIds.join(', ')}`);

  // Write daily results file (used by pulse-refresh to filter auto-submit)
  const resultsPath = path.join(DATA, `readiness-results-${DATE_STAMP}.json`);
  writeJSON(resultsPath, {
    date:         DATE_STAMP,
    timestamp:    new Date().toISOString(),
    dry_run:      DRY_RUN,
    total:        cards.length,
    passed:       passedIds.length,
    failed:       failedIds.length,
    skipped:      skippedIds.length,
    avg_score:    avgScore,
    avg_grade:    avgGrade,
    passed_ids:   passedIds,
    failed_ids:   failedIds,
    skipped_ids:  skippedIds,
    results:      DRY_RUN ? results : undefined,
  });
  console.log(`[readiness] Written → data/readiness-results-${DATE_STAMP}.json`);
}
